// <auto-generated />
namespace garaget_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class primaryKey_in_VehicleType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primaryKey_in_VehicleType));
        
        string IMigrationMetadata.Id
        {
            get { return "201510291114300_primaryKey_in_VehicleType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
